


services:
  - type: web
    name: creamjoy-backend
    runtime: python
    repo: https://github.com/Twesi-001/creamjoy-system
    plan: free
    region: oregon
    branch: main
    rootDir: backend

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app

    envVars:
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DB
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POETRY_VERSION
        value: ""

    healthCheckPath: /health

    autoDeploy: true


